---
name: release

on:
  workflow_dispatch:

env:
  ANSIBLE: "stable-2.15"
  HERE: "./ansible_collections/delinea/ss"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Pull
        uses: actions/checkout@v3
        with:
          path: ${{ env.HERE }}

      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Ansible
        run: sudo apt install ansible

      - name: Build
        run: ansible-galaxy collection build --force
        working-directory: ${{ env.HERE }}

      - name: Install
        run: tar -xzvf /home/runner/work/ansible-ss-collection/ansible-ss-collection/ansible_collections/delinea/ss/delinea-ss-1.0.0.tar.gz -C /path/to/python/package/folder/
        #run: python3.10 -m pip install /home/runner/work/ansible-ss-collection/ansible-ss-collection/ansible_collections/delinea/ss/delinea-ss-1.0.0.tar.gz --force

      - name: PyTest
        run: python3.10 -m pip install pytest

      - name: Run Unit Test
        run: python -m pytest
        working-directory: ${{ env.HERE }}

      #- name: Install Tox
      #  run: |
      #    python -m pip install --upgrade pip
      #    pip install tox

      #- name: Run Tox
      #  # Run tox using the version of Python in `PATH`
      #  run: tox -e py
      #  working-directory: ${{ env.HERE }}
