---
name: release

on:
  # Run CI against all pushes (direct commits, also merged PRs), Pull Requests
  push:
    branches:
      - main
      - stable-*
  pull_request:
  
  workflow_dispatch:
  
env:
  ANSIBLE: "stable-2.15"
  HERE: "./ansible_collections/delinea/ss"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Pull
        uses: actions/checkout@v3
        with:
          path: ${{ env.HERE }}

      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Ansible
        run: sudo apt install ansible

      - name: Build
        run: |
              ansible-galaxy collection build --force
        working-directory: ${{ env.HERE }}

      - name: Get File
        run: |
              generated_file=$(find . -type f -name "delinea-ss-*.tar.gz" | head -n 1)
              echo "FOUND_FILE=$generated_file" >> $GITHUB_ENV
        working-directory: ${{ env.HERE }}

      - name: Upload Ansible Collection Package
        uses: actions/upload-artifact@v1
        with:
          name: delinea-ss-1.0.0.tar.gz
          path: $FOUND_FILE

      #- name: PyTest
      #  run: python -m pip install pytest

      #- name: Run Unit Test
      #  run: python -m pytest
      #  working-directory: ${{ env.HERE }}
